app/main/routes.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user

main = Blueprint('main', __name__)

from app import db
from app.api.models import Word, WordDefinition, Library
from app.utils.word_utils import search_word, add_word_point

@main.route('/')
@main.route('/index')
@login_required
def index():
    count = Library.get_count(current_user.id)
    return render_template('main/index.html', count=count)

@main.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        request_word = request.form.get('word')
        word = Word.query.filter_by(word=request_word).first()
        if word:
            word_in_library = Library.word_exists(current_user.id, word.id)
            word_definitions = WordDefinition.query.filter_by(word_id=word.id).all()
            add_word_point(user_id=current_user.id, word_id=word.id, point=1, reason="search")
            return render_template('main/search.html', word=word, word_definitions=word_definitions, word_in_library=word_in_library)
        else:
            try:
                response = search_word(request_word)
                if response:
                    word = Word(
                        word=response['word'],
                    )
                    db.session.add(word)
                    db.session.commit()
                    word_in_library = Library.word_exists(current_user.id, word.id)
                    for definition in response['results']:
                        word_definition = WordDefinition(
                            word_id=word.id,
                            definition=definition['definition'],
                            part_of_speech=definition['partOfSpeech']
                        )
                        db.session.add(word_definition)
                        db.session.commit()
                    add_word_point(user_id=current_user.id, word_id=word.id, point=1, reason="search")
                    return render_template('main/search.html', word=word, word_definitions=Word.get_definitions(word.id), word_in_library=word_in_library)
            except:
                flash('word or word definition not found', category='error')
    return render_template('main/search.html', word="", word_definitions=[], word_in_library=False)

@main.route('/library')
@login_required
def library():
    library_items = Library.get_all(current_user.id)
    return render_template('main/library.html', library_items=library_items)

@main.route('/practice')
@login_required
def practice():
    count = Library.get_count(current_user.id)
    return render_template('main/practice.html', count=count)

app/templates/navbar/messages.html


{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    {% for category, message in messages %}
      {% if category %}
        <script>
            toastr.{{category}}('{{message}}', { timeOut: 1000 })
        </script>
      {% else %}
        <script>
            toastr.info('{{message}}', { timeOut: 1000 })
        </script>
      {% endif %}
    {% endfor %}
  {% endif %}
{%- endwith %}

app/templates/navbar/navbar.html
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('main.index' ) }}" class="nav-link px-2 link-dark">Dashboard</a></li>
        <li><a href="{{ url_for('main.library' ) }}" class="nav-link px-2 link-dark">My Library</a></li>
        <li><a href="{{ url_for('main.practice' ) }}" class="nav-link px-2 link-dark">Practice</a></li>
      </ul>

      <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
          data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://cdn.iconscout.com/icon/free/png-256/avatar-370-456322.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="{{ url_for('auth.logout' ) }}">Sign out</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>

<header class="py-3 mb-4 border-bottom">
  <form action="{{ url_for('main.search' ) }}" method="post" >
    <div class="container d-flex flex-wrap justify-content-center">
      <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Search Word" aria-label="Search Word"
          aria-describedby="button-addon2" name="word" id="word" {% if word %} value="{{ word.word }}" {% endif %}>
        <button class="btn btn-outline-secondary" type="submit" id="search">Search</button>
      </div>
    </div>
  </form>
</header>